# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='accType',
            new_name='acctype',
        ),
    ]
