# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160801_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=256)),
                ('foodImgUrl', models.TextField()),
                ('foodDescription', models.TextField()),
                ('foodRestaurantId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodId', models.IntegerField()),
                ('customerId', models.IntegerField()),
                ('time', models.IntegerField()),
                ('place', models.CharField(max_length=256)),
                ('accept', models.BooleanField()),
            ],
        ),
    ]
